import sys
def bookchoice():
	print("Hello! I am here today to help you find some books that suite your liking!")
	bookname = (input("What is your name:"))
	print("Okay,",bookname,",time to get started! 🙂 ")
	print("                                   ")
	print("1. What genre do you enjoy most?")
	A =print("Enter A-  'Poetry'")
	B =print("Enter B-  'Drama'")
	C =print("Enter C-  'Fiction'")
	D =print("Enter D-  'Non-Fiction/Historical Fiction'")
	E =print("Enter E-  'Folklore'")
	genre = (input("Enter A,B,C,D,or E: "))
	if genre == 'A' or genre == 'a':
		print("Here are 5 poetry books you should definatley check out:")
		print("1. Milk and Honey By: Rupi Kaur")
		print("2. Oddesy By: Homer ")
		print("3. Hate that Cat and Love that Dog By: Sharon Creech")
		print("4. Where the Sidewalk Ends By: Shel Silverstien")
		print("5. Revolting Rhymes By: Roald Dahl")
		print("                                   ")
		print("Check out these books! I hope you enjoyed",bookname,"!❤❤❤")
	if genre == 'B' or genre == 'b':
		print("Here are 5 Drama books you should definatley check out:")
		print("1. Dead Girls don't Lie By: Jennifer Shaw Wolf ")
		print("2. The Secret Language of Girls Trilogy By: Frances O' Roark Dowell ")
		print("3. Dork Diaries Series By: Rachel Renee Russel")
		print("4. Drama By: Raina Telgemeier")
		print("5. The Fault in Our Stars By: John Green")
		print("                                   ")
		print("Check out these books! I hope you enjoyed",bookname,"!❤❤❤")
	if genre == 'C' or genre == 'c':
		print("Here are 5 Fiction books you should definatley check out:")
		print("1. Harry Potter Series By: J.K. Rowling ")
		print("2. Percy Jackson and The Olympians Series By: Rick Riordan")
		print("3. Under Their Skin and In Over Their Heads By: Margaret Peterson Haddix")
		print("4. Divergent Trilogy By: Veronica Roth")
		print("5. The Hunger Games By: Suzanne Collins")
		print("                                   ")
		print("Check out these books! I hope you enjoyed",bookname,"!❤❤❤")
	if genre == 'D' or genre == 'd':
		print("Here are 5 Non-Fiction/Historical Fiction books you should definatley check out:")
		print("1.Historical Fiction-- Number the Stars By: Lois Lowry   ")
		print("2.Historical Fiction-- Sadako and the Thousand Paper Cranes By: Eleanor Coarr  ")
		print("3.Non-Fiction-- Astrophysics for People in a Hurry By: Neil de Grasse Tyson  ")
		print("4.Non-Fiction-- Hiroshima By: John Hersey ")
		print("5.Historical Fiction-- Bud not Buddy By: Christopher Paul Curtis  ")
		print("                                   ")
		print("Check out these books! I hope you enjoyed",bookname,"!❤❤❤")
	if genre == 'E' or genre == 'e':
		print("Here are 5 Folklore books you should definatley check out:")
		print("1.The Complete World of Greek Mythology By: Richard Buxton  ")
		print("2.The Little Mermaid By: Hans Christian Andersen ")
		print("3.Grimms' Fairy Tales By: Jacob Grimm and Wilhelm Grimm ")
		print("4.The Mythology Book: Big Ideas Simply Explained By:DK ")
		print("5.The Tale of Despereaux By: Kate DiCamillo ")
		print("                                   ")
		print("Check out these books! I hope you enjoyed",bookname,"!❤❤❤")
bookchoice()
